In [2]:
import numpy as np

In [6]:
x_orig = np.random.random_integers(0,10, (3,3,2))
print(x_orig.shape)
print(x_orig)

(3, 3, 2)
[[[ 1  2]
  [ 2  5]
  [ 9  8]]

 [[ 6  4]
  [10  3]
  [ 2 10]]

 [[ 3  2]
  [ 7  2]
  [ 2  6]]]


/tmp/ipykernel_13710/1992790965.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 10 + 1) instead
  x_orig = np.random.random_integers(0,10, (3,3,2))


In [14]:
x_flatten = x_orig.reshape(x_orig.shape[0], -1).T
print(x_flatten)
x_flatten2 = x_orig.reshape(x_orig.shape[1] * x_orig.shape[2], x_orig.shape[0])
print(x_flatten2)

[[ 1  6  3]
 [ 2  4  2]
 [ 2 10  7]
 [ 5  3  2]
 [ 9  2  2]
 [ 8 10  6]]
[[ 1  2  2]
 [ 5  9  8]
 [ 6  4 10]
 [ 3  2 10]
 [ 3  2  7]
 [ 2  2  6]]
